drug/urls.py
from django.urls import path, include
from drug import views


app_name = "drug"

urlpatterns = [
    path('', views.DrugList.as_view(), name='list'),
    path('<pharmacy>/drugs/', views.DrugsPharmacy.as_view(), name='pharmacy_drugs'),

    # adding drug to cart
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # remove drug from cart
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_drug_from_cart/<slug>/', views.remove_single_drug_from_cart, name='remove_single_drug_from_cart'),

    # view cart
    path('order-summary/', views.OrderSummary.as_view(), name='order_summary'),

    # CRUD urls
    path('register/', views.DrugRegister.as_view(), name='register'),
    path('<slug>/', views.DrugDetail.as_view(), name='detail'),
    path('<slug>/edit/', views.DrugEdit.as_view(), name='edit'),
    path('<slug>/delete/', views.DrugDelete.as_view(), name='delete'),

    # list of expired drugs
    path('<pharmacy>/expired_drugs/', views.DrugsExpired.as_view(), name='expired_drugs'),
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),

    # landing url
    path('', views.LandingView.as_view(), name='landing'),

    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    # auth urls
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from search import views


app_name = 'search'

urlpatterns = [
    path('', views.DrugSearchListView.as_view(), name="list"),
    path('pharmacist_list', views.PharmacistSearchListView.as_view(),
         name="pharmacist_list"),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
# from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render

# Create your views here.
from django.views import generic

from drug.models import Drugs
from core.models import Pharmacy
from pms.settings import AUTH_USER_MODEL
from core.permissions.mixins import AdminPermissionRequiredMixin, PharmacistPermissionRequiredMixin


User = AUTH_USER_MODEL


class DrugSearchListView(LoginRequiredMixin, generic.ListView):
    template_name = 'search/view.html'
    paginate_by = 5
    context_object_name = 'drugs'

    def get_context_data(self, **kwargs):
        context = super(DrugSearchListView, self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        context['pharmacy'] = Pharmacy.objects.filter(
            name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(
            pharmacy=self.request.user.pharmacyuser.works_at)
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')

        if query is not None:
            return Drugs.objects.search(query)
        return Drugs.objects.none()


class PharmacistSearchListView(LoginRequiredMixin, generic.ListView):
    template_name = 'search/pharmacist_list.html'
    paginate_by = 5
    context_object_name = 'pharmacists'
    model = User

    def get_context_data(self, **kwargs):
        context = super(DrugSearchListView, self).get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        context['pharmacy'] = Pharmacy.objects.filter(
            name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(
            pharmacy=self.request.user.pharmacyuser.works_at)
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')

        if query is not None:
            return User.objects.search_pharmacist(query)
        return Drugs.objects.none()

search/templates/search/pharmacist_list.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "List of Pharmacist" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/list.css' %}" />
<link rel="stylesheet" href="{% static 'drug/css/search.css' %}" />
<link rel="stylesheet" href="{% static 'base/css/footer.css' %}" />

{% endblock %}

{% block content %}

<div class="search">
    {% include 'search/snippets/search_pharmacist.html' %}
</div>

<div class="list_header">

    <h1>Searched for {{ query }}</h1>

    {% if request.user.is_superuser %}
    <p>Overall Drug count: {{ drug_count }}</p>
    {% endif %}

</div>

<br />


<div class="main">
    {% if query %}

    <div class="drug_container">

        {% for phamacist in pharmacists %}

        <div class="drug_item">
            <span class="top"></span>
            {% if phamacist.profile.image.url is not null %}
            <div class="image">
                <img src="{{ phamacist.profile.image.url }}" alt="image" />
            </div>
            {% endif %}
            <div>
                <p>
                    Brand name: <span>{{ phamacist.email }}</span>
                </p>
            </div>
            {% if drug.generic_name %}
            <div>
                <p>
                    Generic name: <span>{{ phamacist.first_name }}</span>
                </p>
            </div>
            {% endif %}
            <div>
                <p>
                    Category: <span>{{ phamacist.last_name }}</span>
                </p>
            </div>

            
            <a href="{% url 'drug:detail' slug=drug.slug %}"><span><i class="fa fa-eye"></i>View</span></a>
            <span class="bottom"></span>
        </div>

        {% empty %}

        <p class="not_present">The drug {{ query }} does not exist</p>

    </div>


    {% endfor %}

    {% else %}

    <p class="not_present">The drug {{ query }} does not exist</p>

    {% endif %}
</div>

<br />

{% if is_paginated %}
<ul class="pagination">

    {% if page_obj.has_previous %}
    <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-circle-left"></i></a>
    </li>
    {% else %}
    <li class="disabled arrow"><span><i class="fa fa-chevron-circle-left"></i></span></li>
    {% endif %}

    {% for i in paginator.page_range %}

    {% if page_obj.number == i %}
    <li class="active">
        <span>{{ i }} <span class="sr-only">(current)</span></span>
    </li>
    {% else %}
    <li>
        <a href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
    <li class="arrow"><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-circle-right"></i></a>
    </li>
    {% else %}
    <li class="disabled arrow"><span><i class="fa fa-chevron-circle-right"></i></span></li>
    {% endif %}

</ul>
{% endif %}


{% endblock %}

{% block extra_body %}

{% include "core/base/footer.html" %}

{% endblock %}

{% block js %}

<script src="{% static 'drug/js/list.js' %}"></script>

{% endblock %}

search/templates/search/view.html
{% extends "account/base.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "Drug List" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/list.css' %}" />
<link rel="stylesheet" href="{% static 'drug/css/search.css' %}" />
<link rel="stylesheet" href="{% static 'base/css/footer.css' %}" />

{% endblock %}

{% block content %}

<div class="search">
    {% include 'search/snippets/search-form.html' %}
</div>

<div class="list_header">

    <h1>Searched for {{ query }}</h1>

    {% if request.user.is_superuser %}
    <p>Overall Drug count: {{ drug_count }}</p>
    {% endif %}

</div>

<br />


<div class="main">
    {% if query %}

    <div class="drug_container">

        {% for drug in drugs %}

        <div class="drug_item">
            <span class="top"></span>
            {% if drug.image.url is not null %}
            <div class="image">
                <img src="{{ drug.image.url }}" alt="image" />
            </div>
            {% endif %}
            <div>
                <p>
                    Brand name: <span>{{ drug.brand_name }}</span>
                </p>
            </div>
            {% if drug.generic_name %}
            <div>
                <p>
                    Generic name: <span>{{ drug.generic_name }}</span>
                </p>
            </div>
            {% endif %}
            <div>
                <p>
                    Category: <span>{{ drug.category }}</span>
                </p>
            </div>

            {% if drug.discount_price %}
            <div>
                <p>
                    Discount Price: <span>{{ drug.discount_price }} CFA</span>
                </p>
            </div>
            <div>
                <p>
                    Price: <span class="cross">{{ drug.price }} CFA</span>
                </p>
            </div>
            {% else %}
            <div>
                <p>
                    Price: <span class="cross">{{ drug.price }} CFA</span>
                </p>
            </div>
            {% endif %}
            <a href="{% url 'drug:detail' slug=drug.slug %}"><span><i class="fa fa-eye"></i>View</span></a>
            <span class="bottom"></span>
        </div>

        {% empty %}

        <p class="not_present">The drug {{ query }} does not exist</p>

    </div>


    {% endfor %}

    {% else %}

    <p class="not_present">The drug {{ query }} does not exist</p>

    {% endif %}
</div>

<br />

{% if is_paginated %}
<ul class="pagination">

    {% if page_obj.has_previous %}
    <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-circle-left"></i></a>
    </li>
    {% else %}
    <li class="disabled arrow"><span><i class="fa fa-chevron-circle-left"></i></span></li>
    {% endif %}

    {% for i in paginator.page_range %}

    {% if page_obj.number == i %}
    <li class="active">
        <span>{{ i }} <span class="sr-only">(current)</span></span>
    </li>
    {% else %}
    <li>
        <a href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
    <li class="arrow"><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-circle-right"></i></a>
    </li>
    {% else %}
    <li class="disabled arrow"><span><i class="fa fa-chevron-circle-right"></i></span></li>
    {% endif %}

</ul>
{% endif %}


{% endblock %}

{% block extra_body %}

{% include "core/base/footer.html" %}

{% endblock %}

{% block js %}

<script src="{% static 'drug/js/list.js' %}"></script>

{% endblock %}