core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    # path('base/', views.BaseIndexView.as_view(), name='base_dashbaord'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('signup/', SignUpView.as_view(), name='register'),
    # path('login/', login_view, name='login')
    path('<name>/profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.profile, name='profile_update'),

    # pharmacy create
    path('pharmacy_create/', views.PharmacyRegister.as_view(), name='pharmacy_create'),

    # list of pharmacy users in my pharmacy
    path('<pharmacy>/pharmacists/', views.PharmacistList.as_view(), name='pharmacist_list'),
    path('is_pharmacist/', views.pharmacist_add, name='pharmacist_add')
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),

    # landing url
    path('', views.LandingView.as_view(), name='landing'),

    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    # auth urls
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext_lazy as _
from allauth.account.models import EmailAddress
from django.urls import reverse

# from drug.models import Drug, Category
# from core.permissions.permissions import ROLE_LIST, role as user_role


# Create your models here.
from pms import settings


class City(models.Model):
    name = models.CharField(
        max_length=50)

    created_on = models.DateTimeField(_('added on'), auto_now_add=True)
    updated_on = models.DateTimeField(_('updated on'), auto_now=True)

    class Meta:
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Pharmacy(models.Model):
    name = models.CharField(
        max_length=100, help_text="Enter the name of your pharmacy")
    location = models.CharField(max_length=100)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    phone = PhoneNumberField(_('phone number'), blank=True, help_text=_(
        'Number must be in format: +237654686473'))

    created_on = models.DateTimeField(_('added on'), auto_now_add=True)
    updated_on = models.DateTimeField(_('updated on'), auto_now=True)

    class Meta:
        verbose_name_plural = 'Pharmacies'

    def get_absolute_url(self):
        return reverse('drug:list')

    def __str__(self):
        return self.name


class UserQueryset(models.query.QuerySet):

    def search_pharmacist(self, query):
        instances = self.filter()
        lookups = Q(email__icontains=query) | Q(first_name__icontains=query) | Q(
            last_name__icontains=query)
        return self.filter(lookups).distinct()


class UserManager(models.Manager):
    def get_queryset(self):
        return UserQueryset(self.model, using=self._db)

    def search_pharmacist(self, query):
        return self.get_queryset().all().search_pharmacist(query)


class User(AbstractUser):
    is_admin = models.BooleanField(default=False)
    is_pharmacist = models.BooleanField(default=False)

    # username = None
    email = models.EmailField(
        unique=True, verbose_name='Email', help_text='Enter email')
    address = models.CharField(max_length=100, help_text='Enter your area of residence', verbose_name='Address',
                               blank=True, null=True)
    phone = PhoneNumberField(_('phone number'), blank=True, help_text=_(
        'Number must be in international format.'), null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    # objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    @property
    def email_addresses(self):
        return EmailAddress.objects.filter(user__pk=self.pk)

    @property
    def is_verified(self):
        return EmailAddress.objects.filter(verified=True).exists()


class PharmacyUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    works_at = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    created_on = models.DateTimeField(_('added on'), auto_now_add=True)
    updated_on = models.DateTimeField(_('updated on'), auto_now=True)

    # class Meta:
    #     unique_together = (('user', 'works_at'),)

    # def __str__(self):
    #     return f'{self.user.email} | {self.works_at.name} in {self.city.name}'

    def __str__(self):
        return self.user.email


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True, related_name='profile')
    image = models.ImageField(upload_to='profile/',
                              default='profile/default_profile.jpg')

    created_on = models.DateTimeField(_('added on'), auto_now_add=True)
    updated_on = models.DateTimeField(_('updated on'), auto_now=True)

    def __str__(self):
        return self.user.email

core/forms.py
# from allauth.account.forms import SetPasswordField, PasswordField
from django import forms
from core.models import User, Profile, Pharmacy

# from phonenumber_field.modelfields import PhoneNumberField
# from django.utils.translation import ugettext_lazy as _


class SignupForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(
        attrs={"class": "input_text", }), required=True,)
    first_name = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={"class": "input_text", }), required=True,)
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={"class": "input_text", }), required=False)
    address = forms.CharField(max_length=100)
    phone = forms.CharField(help_text="Number must be in format: +237654686473", label="Phone Number",
                            max_length=30, widget=forms.TextInput(attrs={"class": "input_text", }))

    class Meta:
        model = User

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.address = self.cleaned_data['address']
        user.phone = self.cleaned_data['phone']
        user.save()


class UserProfile(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone', 'address']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class PharmacyCreateForm(forms.ModelForm):
    class Meta:
        model = Pharmacy
        fields = '__all__'
        widgets = {'location': forms.HiddenInput(),
                   'city': forms.HiddenInput()}

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.gis.geoip2.resources import City
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic

from core import forms
from core.models import Pharmacy, PharmacyUser, User
from core.permissions.mixins import (AdminPermissionRequiredMixin,
                                     PharmacistPermissionRequiredMixin,
                                     admin_required_permission,
                                     pharmacist_required_permission)
from drug.models import Drugs

# class BaseIndexView(LoginRequiredMixin, PharmacistPermissionRequiredMixin, AdminPermissionRequiredMixin, generic.TemplateView):
#     template_name = "base_dashboard.html"
#     model = Drugs
#     paginate_by = 5
#     context_object_name = 'drugs'
#     queryset = Drugs.objects.all()

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['pharmacy'] = Pharmacy.objects.filter(name=self.request.user.pharmacyuser.works_at)[0]
#         context['pharmacy_drugs'] = Drugs.objects.filter(pharmacy=self.request.user.pharmacyuser.works_at)
#         # print(context.get('pharmacy'))
#         return context


class LandingView(generic.TemplateView):
    template_name = "core/landing.html"
    model = Drugs
    # paginate_by = 5
    context_object_name = 'drugs'
    queryset = Drugs.objects.all()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['pharmacy'] = Pharmacy.objects.filter(
    #         name=self.request.user.pharmacyuser.works_at)[0]
    #     context['pharmacy_drugs'] = Drugs.objects.filter(
    #         pharmacy=self.request.user.pharmacyuser.works_at)
    #     return context


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = "core/index.html"
    model = Drugs
    paginate_by = 5
    context_object_name = 'drugs'
    queryset = Drugs.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pharmacy'] = Pharmacy.objects.filter(
            name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(
            pharmacy=self.request.user.pharmacyuser.works_at)
        return context


class UserProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/profile.html'
    model = User
    queryset = User.objects.all()

    def get_context_data(self, **kwargs):
        context = super(UserProfile, self).get_context_data(**kwargs)
        context['pharmacy'] = Pharmacy.objects.filter(
            name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(
            pharmacy=self.request.user.pharmacyuser.works_at)
        return context


# editing user profile
@login_required()
def profile(request):
    if request.method == 'POST':
        u_form = forms.UserProfile(request.POST, instance=request.user)
        p_form = forms.ProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Profile was successfully updated')
            return redirect('core:profile', name=request.user.first_name)

    else:
        u_form = forms.UserProfile(instance=request.user)
        p_form = forms.ProfileForm(instance=request.user.profile)

    context = {
        'form1': u_form,
        'form2': p_form,
        'pharmacy': Pharmacy.objects.filter(name=request.user.pharmacyuser.works_at)[0],
        'pharmacy_drugs': Drugs.objects.filter(pharmacy=request.user.pharmacyuser.works_at)
    }

    return render(request, 'core/profile_update.html', context)


class PharmacyRegister(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.CreateView):
    template_name = 'core/pharmacy_create.html'
    model = Pharmacy
    form_class = forms.PharmacyCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pharmacy'] = Pharmacy.objects.filter(
            name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(
            pharmacy=self.request.user.pharmacyuser.works_at)
        # print(context.get('pharmacy'))
        return context

   # overridding form field input
    def get_initial(self):
        initial = super(PharmacyRegister, self).get_initial()
        self.kwargs['location'] = self.request.user.pharmacyuser.works_at.location
        self.kwargs['city'] = self.request.user.pharmacyuser.city
        initial['location'] = self.kwargs.get("location")
        initial['city'] = self.kwargs.get("city")
        return initial

    def form_valid(self, form):
        request = self.request
        form.save(commit=True)
        name = form.cleaned_data['name']
        messages.success(
            request, f'{name} Pharmacy was successfully created!!!')
        return super(PharmacyRegister, self).form_valid(form)


class PharmacistList(LoginRequiredMixin, AdminPermissionRequiredMixin, generic.ListView):
    template_name = 'core/pharmacist_list.html'
    model = PharmacyUser
    paginate_by = 6
    context_object_name = 'pharmacy_users'

    def get_queryset(self):
        pharmacy = Pharmacy.objects.get(
            name=self.request.user.pharmacyuser.works_at)
        users = PharmacyUser.objects.filter(works_at=pharmacy)
        return users

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pharmacy'] = Pharmacy.objects.filter(
            name=self.request.user.pharmacyuser.works_at)[0]
        context['pharmacy_drugs'] = Drugs.objects.filter(
            pharmacy=self.request.user.pharmacyuser.works_at)
        # print(context.get('pharmacy'))
        return context


@login_required(login_url=reversed('account_login'))
@admin_required_permission
def pharmacist_add(request):
    if request.method == 'POST':
        print(request.POST)
        user_id = request.POST.get('pharmacist_id')
        user = get_object_or_404(User, id=user_id)
        pharmacy = Pharmacy.objects.get(
            name=request.user.pharmacyuser.works_at)
        if user.is_pharmacist:
            user.is_pharmacist = False
            messages.success(
                request, f'{user.email} was successfully removed as a pharmacist to "{pharmacy}" pharmacy')
        else:
            user.is_pharmacist = True
            messages.success(
                request, f'{user.email} was successfully added as a pharmacist to "{pharmacy}" pharmacy')
        user.save()
        return redirect('core:pharmacist_list', pharmacy=pharmacy)
    else:
        return Http404("Forbidden request type")

    # try:
    #     product_id = request.POST.get('product_id')
    # except Products.DoesNotExist:
    #     print('product does not exist')
    #     return redirect('cart:home')
    # product_obj = Products.objects.get(id=product_id)
    # cart_obj, new_obj = Cart.objects.new_or_get(request)
    #
    # if product_obj in cart_obj.products.all():
    #     cart_obj.products.remove(product_obj)
    # else:
    #     cart_obj.products.add(product_obj)
    #
    # return redirect('cart:home')

core/templates/core/index.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block title %}{% trans "Dashboard" %}{% endblock %}

{% block css %}


{% endblock %}

{% block content %}

<div class="welcome">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="content">
                    <h2>Welcome {{ request.user.first_name }} to your Dashboard</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="my_content"></div>

{% endblock %}

{% block js %}


{% endblock %}

core/templates/core/landing.html
{% extends "account/base.html" %} {% load i18n %} {% load static %} {% load
account socialaccount %} {% block head_title %}{% trans "pms" %}{% endblock %}

{% block css %}

<!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" />
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->

<link rel="stylesheet" href="{% static 'base/css/landing.css' %}" />
<link rel="stylesheet" href="{% static 'base/css/footer.css' %}" />

{% endblock %}

{% block content %}
<div class="landing_content">
    <div class="first_img">
        <h2 class="right animatable">" PMS, Your health our priority "</h2>

        <!-- <div class="img">
            <img src="{% static 'drug/img/pharmacy.jpg' %}" alt="img">
        </div> -->
        <div class="info left animatable">
            <p>Long gone the frustration and doubts in the questionable integrity and availability of drugs in
                pharmacies
                by users.</p>
            <p>Thanks to PMS, all your worries and doubts are brought to null</p>
        </div>
    </div>

    <div class="get_started">
        <div class="get_started_content">
            <div class="image">
                <img src="{% static 'base/img/question2.gif' %}" alt="image">
            </div>
            <p>Why move from one pharmacy to another in search of a particular Drug?</p>
            <p>why the stress on preparing a drug order list and management of expired drugs?</p>
            <a href="{% url 'account_signup' %}" class="button bottom animatable"><span><i
                        class="fa fa-rocket"></i></span>
                Get Started</a>
        </div>
    </div>

</div>

{% endblock %}

{% block extra_body %}

{% include "core/base/footer.html" %}

{% endblock %}

{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>
<script src="{% static 'base/js/landing.js' %}"></script>

{% endblock %}

core/templates/core/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
</body>
</html>

core/templates/core/pharmacist_list.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block title %}{% trans "List of Pharmacist" %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'base/css/pharmacist_list.css' %}" />
{% endblock %}

{% block content %}

<div class="search">
  {% include 'search/snippets/search-pharmacist.html' %}
</div>

{% blocktrans with pharmacy=request.user.pharmacyuser.works_at city=request.user.pharmacyuser.city %}
<h1>List of users in "{{ pharmacy }}" Pharmacy found in the city of "{{ city }}"</h1>
{% endblocktrans %}


<br>

<div class="pharmacist_list">

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone Number</th>
        <th>Profile Pic</th>
        <th>Is Pharmacist</th>
      </tr>
    </thead>
    <tbody>
      {% for pharmacy_user in pharmacy_users %}
      <tr>
        <td>{{ pharmacy_user.user.email }}</td>
        <td>{{ pharmacy_user.user.first_name }}</td>
        <td>{{ pharmacy_user.user.last_name }}</td>
        <td>{{ pharmacy_user.user.phone }}</td>
        <td>
          <div class="img">
            <img src="{{ pharmacy_user.user.profile.image.url }}" alt="profile">
          </div>
        </td>
        <td>
          <form action="{% url 'core:pharmacist_add' %}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{ pharmacy_user.user.id }}" name="pharmacist_id">

            {% if pharmacy_user.user.is_pharmacist %}

            <button class="button remove" type="submit"><span><i class="fa fa-trash"></i></span> Remove</button>

            {% else %}

            <button class="button add" type="submit"><span><i class="fa fa-user-plus"></i></span> Add</button>

            {% endif %}

          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

<br>

{% if is_paginated %}
<ul class="pagination">

  {% if page_obj.has_previous %}
  <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-circle-left"></i></a>
  </li>
  {% else %}
  <li class="disabled arrow"><span><i class="fa fa-chevron-circle-left"></i></span></li>
  {% endif %}

  {% for i in paginator.page_range %}

  {% if page_obj.number == i %}
  <li class="active">
    <span>{{ i }} <span class="sr-only">(current)</span></span>
  </li>
  {% else %}
  <li>
    <a href="?page={{ i }}">{{ i }}</a>
  </li>
  {% endif %}

  {% endfor %}

  {% if page_obj.has_next %}
  <li class="arrow"><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-circle-right"></i></a>
  </li>
  {% else %}
  <li class="disabled arrow"><span><i class="fa fa-chevron-circle-right"></i></span></li>
  {% endif %}

</ul>
{% endif %}


{% endblock %}

{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>

{% endblock %}

core/templates/core/pharmacy_create.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block title %}{% trans "Register Pharmacy" %}{% endblock %}

{% block css %}

<link rel="stylesheet" href="{% static 'accounts/css/pharmacy_create.css' %}" />

{% endblock %}

{% block content %}

<div class="pharmacy_register">

    <h2 style="color: #fff">Register Pharmacy</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="group">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            <span class="icon"><i class="fa fa-edit"></i></span>
            {{ form.name }}
            <div class="alert_error">
                {{ form.name.errors }}
            </div>
            <span class="helptext">{{ form.name.help_text }}</span>
        </div>

        <div class="group">
            <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
            <span class="icon"><i class="fa fa-phone"></i></span>
            {{ form.phone }}
            <div class="alert_error">
                {{ form.phone.errors }}
            </div>
            <span class="helptext">{{ form.phone.help_text }}</span>
        </div>

        <!-- displaying hidden input fields for Pharmacy location and city -->
        {% for hidden_field in form.hidden_fields %}
        {% if hidden_field.errors %}
        <ul>
            {% for error in hidden_field.errors %}
            <li>(Hidden Field {{ hidden_field.name }}) {{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {{ hidden_field }}
        {% endfor %}


        <div class="submit">
            <button class="button" type="submit">
                <span><i class="fa fa-database"></i></span> Register
            </button>
        </div>
    </form>

</div>

{% endblock %}

{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>

{% endblock %}

core/templates/core/profile.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block title %}{% trans "Profile Update" %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}" />
{% endblock %}

{% block content %}


<div class="profile_content">
    <div class="profile_heading">
        <h2>User Profile</h2>
        <!-- <a href="#">Edit</a> -->
    </div>
    <div class="profile_one">
        <img src="{{ request.user.profile.image.url }}" alt="image">
        <p>{{ request.user.first_name }} {{ request.user.last_name }}</p>
    </div>
    <div class="profile_two">
        <table>
            <tbody>
                <tr>
                    <td>First Name: </td>
                    <td>{{ request.user.first_name }}</td>
                </tr>
                <tr>
                    <td>Last Name: </td>
                    <td>{{ request.user.last_name }}</td>
                </tr>
                <tr>
                    <td>Email: </td>
                    <td>{{ request.user.email }}</td>
                </tr>
                <tr>
                    <td>Phone Number: </td>
                    <td>{{ request.user.phone }}</td>
                </tr>
                <tr>
                    <td>Address: </td>
                    <td>{{ request.user.pharmacyuser.city }}</td>
                </tr>

                {% if request.user.is_admin or request.user.is_pharmacist %}

                <tr>
                    <td>Works At: </td>
                    <td>{{ request.user.pharmacyuser.works_at }} pharmacy in {{ request.user.pharmacyuser.city }} </td>
                </tr>

                {% endif %}
            </tbody>
        </table>
    </div>
    <div class="profile_three">
        <a class="button" href="{% url 'core:profile_update' %}"><span><i class="fa fa-gear"></i></span> Edit</a>
    </div>
</div>

{% endblock %}

{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>

{% endblock %}

core/templates/core/profile_update.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block title %}{% trans "Profile Update" %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/profile_update.css' %}" />
{% endblock %}

{% block content %}

<div class="profile_update">

    <h2 style="color: #fff">Profile update</h2>

    <div class="profile_content">

        <div class="img">
            <img onchange="PreviewImage()" src=" {{ request.user.profile.image.url }}" alt="profile">
        </div>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form1.as_p }}
            {{ form2.as_p }}

            <div class="submit">
                <button class="button" type="submit"><span><i class="fa fa-database"></i></span> Save</button>
            </div>
        </form>

    </div>

</div>

{% endblock %}

{% block js %}
<script src="{% static 'base/js/button.js' %}"></script>
<script src="{% static 'accounts/js/profile_update.js' %}"></script>
{% endblock %}