drug/urls.py
from django.urls import path, include
from drug import views


app_name = "drug"

urlpatterns = [
    path('', views.DrugList.as_view(), name='list'),
    path('<pharmacy>/drugs/', views.DrugsPharmacy.as_view(), name='pharmacy_drugs'),

    # adding drug to cart
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # remove drug from cart
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_drug_from_cart/<slug>/', views.remove_single_drug_from_cart, name='remove_single_drug_from_cart'),

    # view cart
    path('order-summary/', views.OrderSummary.as_view(), name='order_summary'),

    # CRUD urls
    path('register/', views.DrugRegister.as_view(), name='register'),
    path('<slug>/', views.DrugDetail.as_view(), name='detail'),
    path('<slug>/edit/', views.DrugEdit.as_view(), name='edit'),
    path('<slug>/delete/', views.DrugDelete.as_view(), name='delete'),

    # list of expired drugs
    path('<pharmacy>/expired_drugs/', views.DrugsExpired.as_view(), name='expired_drugs'),
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),

    # landing url
    path('', views.LandingView.as_view(), name='landing'),

    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    # auth urls
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

drug/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from djmoney.models.fields import MoneyField

from core.models import City, Pharmacy
from drug.utils import unique_slug_generator
from pms import settings

User = settings.AUTH_USER_MODEL
# Create your models here.


class BankAccount(models.Model):
    balance = MoneyField(max_digits=14, decimal_places=2,
                         default_currency='XAF')


class Category(models.Model):
    name = models.CharField(help_text='category of drug', max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class DrugQueryset(models.query.QuerySet):

    def good_drugs(self):
        drugs = self.all()
        present_date = timezone.now().date()
        good_drugs = []

        for drug in drugs:
            expiry_date = drug.expiry_date

            # gets the number of days difference
            difference = (expiry_date-present_date).days

            if difference > 0:
                good_drugs.append(drug)
                # return drugs.objects.filter(expiry_date=expiry_date)
# drugs.filter(expiry_date=expiry_date)
        return good_drugs

    def bad_drugs(self):
        drugs = self.all()
        present_date = timezone.now().date()
        bad_drugs = []

        for drug in drugs:
            expiry_date = drug.expiry_date

            # gets the number of days difference
            difference = (expiry_date-present_date).days

            if difference < 0:
                bad_drugs.append(drug)

        return bad_drugs

    def search(self, query):
        lookups = Q(generic_name__icontains=query) | Q(
            brand_name__icontains=query) | Q(price__icontains=query)
        return self.filter(lookups).distinct()


class DrugManager(models.Manager):
    def get_queryset(self):
        return DrugQueryset(self.model, using=self._db)

    # def all(self):
    #     return self.get_queryset().good_drugs()

    def expired_drugs(self):
        return self.get_queryset().bad_drugs()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().all().search(query)


class Drugs(models.Model):
    # name = models.CharField(max_length=100, help_text='name of drug')
    brand_name = models.CharField(
        max_length=100, help_text='This is the drug brand name', verbose_name='Brand name')
    generic_name = models.CharField(
        max_length=100, help_text='Drug scientific name (optional)', verbose_name='Generic name', blank=True, null=True)
    des = models.TextField(max_length=1000, verbose_name='Description')
    slug = models.SlugField(blank=True, unique=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True,
                              help_text='please upload drug image here (optional)', default='images/default_drug.png')
    price = models.DecimalField(
        decimal_places=2, max_digits=20, default=0.00)
    discount_price = models.DecimalField(
        decimal_places=2, max_digits=20, null=True, blank=True, help_text="Discount price is optional")
    batch_no = models.IntegerField(
        verbose_name='Batch Number', help_text="Input batch number of the drug")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Select Category')
    pharmacy = models.ForeignKey(
        Pharmacy, on_delete=models.CASCADE, default=None)
    city = models.ForeignKey(City, on_delete=models.CASCADE, default=None)
    active = models.BooleanField(default=True)
    added_by = models.ForeignKey(
        User, on_delete=models.CASCADE, default=None)

    entry_date = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateField(help_text="Date format: yyyy / mm / dd")

    created_on = models.DateTimeField(
        _('registration date'), auto_now_add=True)
    updated_on = models.DateTimeField(_('last updated'), auto_now=True)

    objects = DrugManager()

    def get_add_to_cart_url(self):
        return reverse('drug:add_to_cart', kwargs={'slug': self.slug})

    def get_absolute_url(self):
        return reverse('drug:detail', kwargs={'slug': self.slug})

    # def get_edit_url(self):
    #     return reverse("drug:detail", kwargs={"slug": self.slug})

    def remove_from_cart_url(self):
        return reverse('drug:remove_from_cart', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-created_on']
        verbose_name_plural = 'Drugs'

    def __str__(self):
        return self.brand_name


class OrderDrugs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    drug = models.ForeignKey(Drugs, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.drug.generic_name}'

    class Meta:
        verbose_name_plural = 'Ordered Drugs'

    def get_total_drug_price(self):
        return self.quantity * self.drug.price

    def get_total_discount_drug_price(self):
        return self.quantity * self.drug.discount_price

    def get_amount_saved(self):
        return self.get_total_drug_price() - self.get_total_discount_drug_price()

    def get_final_price(self):
        if self.drug.discount_price:
            return self.get_total_discount_drug_price()
        else:
            return self.get_total_drug_price()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    drugs = models.ManyToManyField(OrderDrugs)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

    # def get_total(self):
    #     total = 0
    #
    #     for drug in self.drugs.all():
    #         total += drug.get_final_price()
    #
    #     return total


class ExpiredDrugs(models.Model):
    drugs = models.ForeignKey(
        Drugs, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Expired Drugs'

drug/forms.py
from drug.models import Drugs, Category
from django import forms
from django.utils import timezone


class DrugRegistration(forms.ModelForm):
    class Meta:
        model = Drugs
        fields = ['brand_name', 'generic_name', 'des', 'category',
                  'price', 'discount_price', 'batch_no', 'image', 'expiry_date']
        # widget = {'expiry_date': forms.DateField(widget=forms.DateInput())}
        input_formats = {'expiry_date': ['%d/%m/%Y %H:%M']}

    # def __init__(self, request, *args, **kwargs):
    #     # question_pk = kwargs.pop('question_pk')
    #     user_pharmacy = request.user.pharmacyuser.works_at.name
    #     super(DrugRegistration, self).__init__(*args, **kwargs)
    #     if request:
    #         self.fields['pharmacy'].initial = user_pharmacy
    #         self.fields['pharmacy'].widget = forms.HiddenInput()

    def clean_expiry_date(self):
        drug_name = self.cleaned_data['generic_name']
        expiry_date = self.cleaned_data['expiry_date']
        present_date = timezone.now().date()
        # gets the number of days difference
        difference = int(str(expiry_date - present_date).split()[0])
        if difference < 1:
            raise forms.ValidationError(
                "The drug '{}' is expired".format(drug_name))
        elif difference < 7:
            raise forms.ValidationError(
                "The drug '{}' expiration date is too close".format(drug_name))
        else:
            return expiry_date

drug/templates/drug/confirm_delete.html
{% extends "account/base.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "Confirm Delete" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/confirm_delete.css' %}" />
<link rel="stylesheet" href="{% static 'base/css/footer.css' %}" />

{% endblock %}

{% block content %}

<div class="confirm_delete">

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ drug.brand_name }}"?</p>

        <button class="button red" type="submit"><span><i class="fa fa-trash"></i></span> Confirm</button>
    </form>

</div>

{% endblock %}


{% block extra_body %}

{% include "core/base/footer.html" %}

{% endblock %}



{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>

{% endblock %}

drug/templates/drug/detail.html
{% extends "account/base.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "Drug Detail" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/detail.css' %}" />
<link rel="stylesheet" href="{% static 'base/css/footer.css' %}" />

{% endblock %}

{% block content %}

<div class="list_header">

        <h1>{% trans "Drug Detail" %}</h1>

        {% if request.user.is_superuser %}
        <p>Overall Drug count: {{ drug_count }}</p>
        {% endif %}

</div>

<br />

<div class="drug_container">

        <div class="content">

                {% if drug.image.url is not null %}
                <div class="img">
                        <img src="{{ drug.image.url }}" alt="image">
                </div>
                {% endif %}

                <div>
                        <div class="item">
                                <div>
                                        <h4>Brand Name</h4>
                                        <p>{{ drug.brand_name }}</p>

                                </div>
                                <div>
                                        <h4>Generic Name</h4>
                                        <p>{{ drug.generic_name }}</p>

                                </div>
                                <div>
                                        <h4>Drug Description</h4>
                                        <p>{{ drug.des }}</p>

                                </div>
                                <div>
                                        <h4>Category</h4>
                                        <p>{{ drug.category }}</p>

                                </div>
                                <div>
                                        <h4>Pharmacy</h4>
                                        <p>{{ drug.pharmacy }} pharmacy in {{ drug.pharmacy.city }} precisely in
                                                {{ drug.pharmacy.location }}.</p>

                                </div>
                                <div>
                                        <h4>Pharmacy Contact</h4>
                                        <p>{{ drug.pharmacy.phone }}</p>

                                </div>

                                {% if drug.discount_price %}

                                <div>
                                        <h4>Discount Price</h4>
                                        <p>{{ drug.discount_price }} CFA</p>

                                </div>

                                {% else %}

                                <div>
                                        <h4>Drug Price</h4>
                                        <p>{{ drug.price }} CFA</p>

                                </div>

                                {% endif %}

                                <div>
                                        <h4>Batch Number</h4>
                                        <p>{{ drug.batch_no }}</p>

                                </div>
                                <div>
                                        <h4>Expiry Date</h4>
                                        <p>{{ drug.expiry_date }}</p>

                                </div>
                        </div>

                        {% if request.user.is_pharmacist %}
                        <div class="cart">
                                <a class="button" href="{{ object.get_add_to_cart_url }}"><span><i
                                                        class="fa fa-cart-plus"></i></span>
                                        Add to Cart</a><br>
                                <a class="button" href="{{ object.remove_from_cart_url }}"><span><i
                                                        class="fa fa-cart-plus"></i></span>
                                        Remove from Cart</a>
                        </div>
                        {% endif %}
                </div>
        </div>

        {% if request.user.is_admin %}
        <div class="edit">
                <a class="button" href="{% url 'drug:edit' slug=drug.slug %}"><span><i class="fa fa-gear"></i></span>
                        Edit</a>
                <a class="button red" href="{% url 'drug:delete' slug=drug.slug %}"><span><i
                                        class="fa fa-trash"></i></span>
                        Delete</a>
        </div>
        {% endif %}
</div>


{% endblock %}


{% block extra_body %}

{% include "core/base/footer.html" %}

{% endblock %}



{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>
<script src="{% static 'drug/js/detail.js' %}"></script>

{% endblock %}

drug/templates/drug/drug_pharmacy.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "Expired Drugs" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/list.css' %}" />
<link rel="stylesheet" href="{% static 'drug/css/expired.css' %}" />
<link rel="stylesheet" href="{% static 'drug/css/drug_pharmacy.css' %}" />

{% endblock %}

{% block content %}

<div class="search">
  {% include 'search/snippets/search-form.html' %}
</div>

<div class="list_header">

  <h1>Here are the drugs added by {{ request.user }}</h1>

  {% if request.user.is_superuser %}
  <p>Overall Drug count: {{ drug_count }}</p>
  {% endif %}

</div>

<br>

<div class="drug_container">
  {% for drug in drugs %}
  <div class="drug_item">
    <span class="top"></span>
    {% if drug.image.url is not null %}
    <div class="image">
      <img src="{{ drug.image.url }}" alt="image" />
    </div>
    {% endif %}
    <div>
      <p>
        Brand name: <span>{{ drug.brand_name }}</span>
      </p>
    </div>
    {% if drug.generic_name %}
    <div>
      <p>
        Generic name: <span>{{ drug.generic_name }}</span>
      </p>
    </div>
    {% endif %}
    <div>
      <p>
        Category: <span>{{ drug.category }}</span>
      </p>
    </div>

    {% if drug.discount_price %}
    <div>
      <p>
        Discount Price: <span>{{ drug.discount_price }} CFA</span>
      </p>
    </div>
    <div>
      <p>
        Price: <span class="cross">{{ drug.price }} CFA</span>
      </p>
    </div>
    {% else %}
    <div>
      <p>
        Price: <span class="cross">{{ drug.price }} CFA</span>
      </p>
    </div>
    {% endif %}
    <a href="{% url 'drug:detail' slug=drug.slug %}"><span><i class="fa fa-eye"></i>View</span></a>
    <span class="bottom"></span>
  </div>
  {% empty %}

  <p>No drugs have expired</p>

  {% endfor %}
</div>



<br />

{% if is_paginated %}
<ul class="pagination">

  {% if page_obj.has_previous %}
  <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-circle-left"></i></a>
  </li>
  {% else %}
  <li class="disabled arrow"><span><i class="fa fa-chevron-circle-left"></i></span></li>
  {% endif %}

  {% for i in paginator.page_range %}

  {% if page_obj.number == i %}
  <li class="active">
    <span>{{ i }} <span class="sr-only">(current)</span></span>
  </li>
  {% else %}
  <li>
    <a href="?page={{ i }}">{{ i }}</a>
  </li>
  {% endif %}

  {% endfor %}

  {% if page_obj.has_next %}
  <li class="arrow"><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-circle-right"></i></a>
  </li>
  {% else %}
  <li class="disabled arrow"><span><i class="fa fa-chevron-circle-right"></i></span></li>
  {% endif %}

</ul>
{% endif %}


{% endblock %}

{% block js %}

<script src="{% static 'drug/js/list.js' %}"></script>

{% endblock %}

drug/templates/drug/edit.html
{% extends "account/base.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "Edit Drug" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/edit.css' %}" />
<link rel="stylesheet" href="{% static 'base/css/footer.css' %}" />

{% endblock %}

{% block content %}

<div class="drug_edit">

    <h2>Edit Drug</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form_content">
            <div class="form1">
                <div class="group">
                    <label for="{{ form.brand_name.id_for_label }}">{{ form.brand_name.label }}</label>
                    <span class="icon"><i class="fa fa-edit"></i></span>
                    {{ form.brand_name }}
                    <div class="alert_error">
                        {{ form.brand_name.errors }}
                    </div>
                    <span class="helptext">{{ form.brand_name.help_text }}</span>
                </div>
                <div class="group">
                    <label for="{{ form.generic_name.id_for_label }}">{{ form.generic_name.label }}</label>
                    <span class="icon"><i class="fa fa-edit"></i></span>
                    {{ form.generic_name }}
                    <div class="alert_error">
                        {{ form.generic_name.errors }}
                    </div>
                    <span class="helptext">{{ form.generic_name.help_text }}</span>
                </div>
                <div class="group des">
                    <label for="{{ form.des.id_for_label }}">{{ form.des.label }}</label><br>
                    {{ form.des }}
                    <div class="alert_error">
                        {{ form.des.errors }}
                    </div>
                    <span class="helptext">{{ form.des.help_text }}</span>
                </div>
                <div class="group category">
                    <label for="{{ form.category.id_for_label }}">{{ form.category.label }}</label><br>
                    {{ form.category }}
                    <span class="helptext">{{ form.category.help_text }}</span>
                </div>
            </div>

            <div class="form2">

                <div class="group price">
                    <label for="{{ form.price.id_for_label }}">{{ form.price.label }}</label>
                    <span class="icon"><i class="fa fa-money"></i></span>
                    {{ form.price }}
                    <div class="alert_error">
                        {{ form.price.errors }}
                    </div>
                    <span class="helptext">{{ form.price.help_text }}</span>
                </div>
                <div class="group">
                    <label for="{{ form.discount_price.id_for_label }}">{{ form.discount_price.label }}</label>
                    <span class="icon"><i class="fa fa-money"></i></span>
                    {{ form.discount_price }}
                    <div class="alert_error">
                        {{ form.discount_price.errors }}
                    </div>
                    <span class="helptext">{{ form.discount_price.help_text }}</span>
                </div>
                <div class="group">
                    <label for="{{ form.batch_no.id_for_label }}">{{ form.batch_no.label }}</label>
                    <span class="icon"><i class="fa fa-hashtag"></i></span>
                    {{ form.batch_no }}
                    <div class="alert_error">
                        {{ form.batch_no.errors }}
                    </div>
                    <span class="helptext">{{ form.batch_no.help_text }}</span>
                </div>
                <div class="group image">
                    <label id="true" for="{{ form.image.id_for_label }}">{{ form.image.label }}</label>
                    <!-- <input type="file" name="image" accept="image/*" id="id_image"> -->
                    {{ form.image }}
                    <span class="icon"><i class="fa fa-photo"></i></span>
                    <div class="alert_error">
                        {{ form.image.errors }}
                    </div>
                    <span class="helptext">{{ form.image.help_text }}</span>
                </div>
                <!-- <div class="date">
                    <label for="{{ form.expiry_date.id_for_label }}">{{ form.expiry_date.label }}</label>
                    <span class="icon"><i class="fa fa-calendar"></i></span>
                    {{ form.expiry_date }}
                    <div class="alert_error">
                        {{ form.expiry_date.errors }}
                    </div>
                    <span class="helptext">{{ form.expiry_date.help_text }}</span>
                </div> -->
            </div>
        </div>

        <div class="submit">
            <button class="button" type="submit">
                <span><i class="fa fa-database"></i></span> Save
            </button>
        </div>

    </form>

</div>

{% endblock %} {% block extra_body %}
{% include "core/base/footer.html" %} {% endblock %} {% block js %}

<script src="{% static 'drug/js/list.js' %}"></script>

{% endblock %}

drug/templates/drug/expired_drugs.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block head_title %}{% trans "Expired Drugs" %}{% endblock %} {% block css %}

<link rel="stylesheet" href="{% static 'drug/css/list.css' %}" />
<link rel="stylesheet" href="{% static 'drug/css/expired.css' %}" />

{% endblock %}

{% block content %}

<div class="list_header">

  <h1>{% trans "List of Expired Drugs" %}</h1>

  {% if request.user.is_superuser %}
  <p>Overall Drug count: {{ drug_count }}</p>
  {% endif %}

</div>

<br>


<div class="drug_container">
  {% for drug in drugs %}
  <div class="drug_item">
    <span class="top"></span>
    {% if drug.image.url is not null %}
    <div class="image">
      <img src="{{ drug.image.url }}" alt="image" />
    </div>
    {% endif %}
    <div>
      <p>
        Brand name: <span>{{ drug.brand_name }}</span>
      </p>
    </div>
    {% if drug.generic_name %}
    <div>
      <p>
        Generic name: <span>{{ drug.generic_name }}</span>
      </p>
    </div>
    {% endif %}
    <div>
      <p>
        Category: <span>{{ drug.category }}</span>
      </p>
    </div>

    {% if drug.discount_price %}
    <div>
      <p>
        Discount Price: <span>{{ drug.discount_price }} CFA</span>
      </p>
    </div>
    <div>
      <p>
        Price: <span class="cross">{{ drug.price }} CFA</span>
      </p>
    </div>
    {% else %}
    <div>
      <p>
        Price: <span class="cross">{{ drug.price }} CFA</span>
      </p>
    </div>
    {% endif %}
    <a href="{% url 'drug:detail' slug=drug.slug %}"><span><i class="fa fa-eye"></i>View</span></a>
    <span class="bottom"></span>
  </div>
  {% empty %}

  <p>No drugs have expired</p>

  {% endfor %}
</div>



<br />

{% if is_paginated %}
<ul class="pagination">

  {% if page_obj.has_previous %}
  <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-circle-left"></i></a>
  </li>
  {% else %}
  <li class="disabled arrow"><span><i class="fa fa-chevron-circle-left"></i></span></li>
  {% endif %}

  {% for i in paginator.page_range %}

  {% if page_obj.number == i %}
  <li class="active">
    <span>{{ i }} <span class="sr-only">(current)</span></span>
  </li>
  {% else %}
  <li>
    <a href="?page={{ i }}">{{ i }}</a>
  </li>
  {% endif %}

  {% endfor %}

  {% if page_obj.has_next %}
  <li class="arrow"><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-circle-right"></i></a>
  </li>
  {% else %}
  <li class="disabled arrow"><span><i class="fa fa-chevron-circle-right"></i></span></li>
  {% endif %}

</ul>
{% endif %}


{% endblock %}

{% block js %}

<script src="{% static 'drug/js/list.js' %}"></script>

{% endblock %}

drug/templates/drug/order_summary.html
{% extends "base_dashboard.html" %} {% load i18n %} {% load static %}
{% block title %}{% trans "Cart" %}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'drug/css/order_summary.css' %}" />
{% endblock %}

{% block content %}

<h1>{% trans "This is the order summary" %}</h1>

<div class="order_content">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Drug Generic Name</th>
                <th>Drug Brand Name</th>
                <th>Price</th>
                <th>Discount Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            {% for order_drug in drug.drugs.all %}

            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ order_drug.drug.generic_name }}</td>
                <td>{{ order_drug.drug.brand_name }}</td>
                <td>{{ order_drug.drug.price }}</td>

                {% if order_drug.drug.discount_price %}

                <td>{{ order_drug.drug.discount_price }}</td>

                {% else %}

                <td>-</td>

                {% endif %}

                <td class="qty">
                    <a class="reduce" href="{% url 'drug:remove_single_drug_from_cart' order_drug.drug.slug %}"><i
                            class="fa fa-minus"></i></a>
                    {{ order_drug.quantity }}
                    <a class="add" href="{% url 'drug:add_to_cart' order_drug.drug.slug %}"><i
                            class="fa fa-plus"></i></a></td>
                <td class="discount">

                    {% if order_drug.drug.discount_price %}

                    {{ order_drug.get_total_discount_drug_price }} CFA

                    <span id="discount">saving {{ order_drug.get_amount_saved }} CFA</span>

                    {% else %}

                    {{ order_drug.get_total_drug_price }} CFA

                    {% endif %}
                </td>

                <td>
                    <a class="button red" href="{% url 'drug:remove_from_cart' order_drug.drug.slug %}"><span><i
                                class="fa fa-trash"></i></span> Remove Drug</a>
                </td>
            </tr>

            {% empty %}

            <tr>
                <td colspan="8">Your cart is Empty</td>
            </tr>

            {% endfor %}

        </tbody>
    </table>

    {% if total %}

    <div class="total">
        <p>Total : <span>{{ total }} CFA</span></p>
    </div>

    {% endif %}

</div>

<!-- print -->
<div class="continue">
    <a class="button" href="{% url 'drug:list' %}"><span><i class="fa fa-list"></i></span> Continue sales</a>
    <a class="button" href="#"><span><i class="fa fa-calendar-check-o"></i></span> Proceed to check out</a>
</div>

</div>

{% endblock %}

{% block js %}

<script src="{% static 'base/js/button.js' %}"></script>

{% endblock %}