core/urls.py
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    # path('base/', views.BaseIndexView.as_view(), name='base_dashbaord'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('signup/', SignUpView.as_view(), name='register'),
    # path('login/', login_view, name='login')
    path('<name>/profile/', views.UserProfile.as_view(), name='profile'),
    path('profile/update/', views.profile, name='profile_update'),

    # pharmacy create
    path('pharmacy_create/', views.PharmacyRegister.as_view(), name='pharmacy_create'),

    # list of pharmacy users in my pharmacy
    path('<pharmacy>/pharmacists/', views.PharmacistList.as_view(), name='pharmacist_list'),
    path('is_pharmacist/', views.pharmacist_add, name='pharmacist_add')
]

drug/urls.py
from django.urls import path, include
from drug import views


app_name = "drug"

urlpatterns = [
    path('', views.DrugList.as_view(), name='list'),
    path('<pharmacy>/drugs/', views.DrugsPharmacy.as_view(), name='pharmacy_drugs'),

    # adding drug to cart
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),

    # remove drug from cart
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_single_drug_from_cart/<slug>/', views.remove_single_drug_from_cart, name='remove_single_drug_from_cart'),

    # view cart
    path('order-summary/', views.OrderSummary.as_view(), name='order_summary'),

    # CRUD urls
    path('register/', views.DrugRegister.as_view(), name='register'),
    path('<slug>/', views.DrugDetail.as_view(), name='detail'),
    path('<slug>/edit/', views.DrugEdit.as_view(), name='edit'),
    path('<slug>/delete/', views.DrugDelete.as_view(), name='delete'),

    # list of expired drugs
    path('<pharmacy>/expired_drugs/', views.DrugsExpired.as_view(), name='expired_drugs'),
]

pms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from core import views


urlpatterns = [
    path('admin/', admin.site.urls),

    # landing url
    path('', views.LandingView.as_view(), name='landing'),

    # path('', views.IndexView.as_view(), name='home'),
    path('home/', views.IndexView.as_view(), name='home'),

    # auth urls
    path('accounts/', include('allauth.urls')),

    # app_urls
    path('core/', include('core.urls')),
    path('drug/', include('drug.urls')),
    path('search/', include('search.urls')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>

<head>

  {% load cart_template_tags %}
  {% load static %}

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}

  <link rel="stylesheet" href="{% static 'accounts/css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'base/css/nav.css' %}" />

  {% block css %}{% endblock %}
</head>

<body>

  <main>
    {% block body %}

    <nav class="nav">
      <div class="logo">
        <img src="{% static 'base/img/logo.png' %}" alt="logo">
        <p>pms</p>
      </div>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'drug:list' %}">Drugs</a>
          <span class="bar"></span>
        </li>
        {% if request.user.is_pharmacist %}
        <li>
          <a href="{% url 'drug:order_summary' %}"><span>{{ request.user|cart_item_count }} </span><i
              class="fa fa-shopping-cart"></i></a>
          <span class="bar"></span>
        </li>
        {% endif %}
        {% if request.user.is_pharmacist or request.user.is_admin %}
        <li>
          <a href="{% url 'home' %}">Dashboard</a>
          <span class="bar"></span>
        </li>
        {% endif %}

        {% if request.user.is_admin or request.user.is_pharmacist %}

        <!-- show notifications -->
        <li class="notify_li">

          <!-- notication bell -->
          <div class="noti_conatiner">
            <ul>
              <li id="noti_Container">
                <div id="noti_Counter"></div>
                <!--SHOW NOTIFICATIONS COUNT.-->

                <!--A CIRCLE LIKE BUTTON TO DISPLAY NOTIFICATION DROPDOWN.-->
                <div id="noti_Button"><i class="fa fa-bell"></i></div>

                <!--THE NOTIFICAIONS DROPDOWN BOX.-->
                <div id="notifications">
                  <h3>Notifications</h3>

                  {% if messages %}
                  <div class="messages">
                    {% if messages %}
                    <ul>
                      {% for message in messages %}
                      <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:
                        {% endif %}
                        {{ message|safe }}
                      </li>
                      {% endfor %}
                    </ul>
                    {% endif %}
                  </div>
                  {% endif %}

                </div>
              </li>
            </ul>
          </div>


        </li>
        {% endif %}

        <li>
          <a href="{% url 'account_logout' %}">Logout</a>
          <span class="bar"></span>
        </li>
        {% else %}

        <li>
          <a href="{% url 'account_login' %}">Login</a>
          <span class="bar"></span>
        </li>
        <li>
          <a href="{% url 'account_signup' %}">SignUp</a>
          <span class="bar"></span>
        </li>
        {% endif %}
      </ul>
    </nav>

    {% block content %}
    {% endblock %}

    {% endblock %}

    {% block extra_body %}
    {% endblock %}

  </main>

  <script src="{% static 'base/js/jquery.js' %}"></script>
  <!-- <script src="{% static 'base/js/base.js' %}"></script> -->
  <script src="{% static 'base/js/notification_bell.js' %}"></script>

  {% block js %}{% endblock %}

</body>

</html>

templates/base_dashboard.html
{% load i18n %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{% static 'accounts/css/font-awesome.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'dashboard/css/nav.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'dashboard/css/main_dashboard.css' %}"
    />
    <link rel="stylesheet" href="{% static 'base/css/datepicker.css' %}" />

    {% block css %} {% endblock %}
  </head>

  <body>
    <aside class="side-nav" id="show-side-navigation1">
      <div class="heading">
        {% if request.user.profile.image.url %}
        <img src="{{ request.user.profile.image.url }}" alt="profile_image" />
        {% else %}
        <img
          src="{% static 'accounts/img/default_profile.jpg' %}"
          alt="profile_image"
        />
        {% endif %}
        <div class="info">
          <h3>
            <a href="{% url 'core:profile' name=request.user.first_name %}">{{
              request.user.first_name
            }}</a>
          </h3>
          <p>
            Login as {% if request.user.is_admin %} Admin with Admin Dashboard
            {% else %} Pharmacist with Pharmacist Dashboard {% endif %}
          </p>
        </div>
      </div>

      <div class="search">
        {% include 'search/snippets/search-form.html' %}
        <!-- <i class="fa fa-search"></i> -->
      </div>

      <ul class="categories">
        <li>
          <i class="fa fa-medkit"></i>
          <a href="#" class="arrow"> Drugs</a>
          <ul class="side-nav-dropdown">
            {% if request.user.is_admin %}

            <li><a href="{% url 'drug:register' %}">New Drug</a></li>
            <li>
              <a href="{% url 'drug:pharmacy_drugs' pharmacy=pharmacy %}"
                >My Drugs</a
              >
            </li>
            <li>
              <a href="{% url 'drug:expired_drugs' pharmacy=pharmacy %}"
                >View expired Drugs</a
              >
            </li>

            {% endif %}

            <li><a href="{% url 'drug:list' %}">All Drugs</a></li>
          </ul>
        </li>

        {% if request.user.is_pharmacist %}

        <li>
          <i class="fa fa-shopping-cart"></i>
          <a href="{% url 'drug:order_summary' %}">View Cart</a>
        </li>

        {% endif %} {% if request.user.is_admin %}

        <li>
          <i class="fa fa-hospital-o"></i>
          <a href="{% url 'core:pharmacy_create' %}">Register Pharmacy</a>
        </li>

        <li>
          <i class="fa fa-group"></i>
          <a href="{% url 'core:pharmacist_list' pharmacy=pharmacy %}"
            >View list of Pharmacists</a
          >
        </li>

        {% endif %}

        <li>
          <i class="fa fa-user"></i>
          <a href="{% url 'core:profile' name=request.user.first_name %}"
            >Profile</a
          >
        </li>

        <li>
          <i class="fa fa-gear"></i>
          <a href="#" class="arrow"> Settings</a>
          <ul class="side-nav-dropdown">
            <li>
              <a class="" href="{% url 'account_change_password' %}"
                >Change Password</a
              >
            </li>
            <!-- <li><a href="{%  url 'account_email' %}">Reset Email</a></li> -->
          </ul>
        </li>
      </ul>
    </aside>

    <section id="contents">
      <nav class="navbar navbar-default">
        <div class="navbar-header mynav">
          <a class="navbar-brand" href="{% url 'home' %}"
            ><span class="main-color"><i class="fa fa-home fa-fw"></i></span
            >Dashboard</a
          >

          <div class="count count-one">
            <p>Total Drugs: 5</p>
          </div>

          <div class="notify_container">
            {% if request.user.is_admin or request.user.is_pharmacist %}

            <!-- notication bell -->
            <div class="noti_conatiner">
              <ul>
                <li id="noti_Container">
                  <div id="noti_Counter"></div>
                  <!--SHOW NOTIFICATIONS COUNT.-->

                  <!--A CIRCLE LIKE BUTTON TO DISPLAY NOTIFICATION DROPDOWN.-->
                  <div id="noti_Button"><i class="fa fa-bell"></i></div>

                  <!--THE NOTIFICAIONS DROPDOWN BOX.-->
                  <div id="notifications">
                    <h3>Notifications</h3>

                    {% if messages %}
                    <div class="messages">
                      {% if messages %}
                      <ul>
                        {% for message in messages %}
                        <li
                          {%
                          if
                          message.tags
                          %}
                          class="{{ message.tags }}"
                          {%
                          endif
                          %}
                        >
                          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR
                          %}Important: {% endif %}
                          {{ message | safe }}
                        </li>
                        {% endfor %}
                      </ul>
                      {% endif %}
                    </div>
                    {% endif %}
                  </div>
                </li>
              </ul>
            </div>

            {% endif %}

            <div class="logout">
              <a href="{% url 'account_logout' %}">Logout</a>
              <span class="bar"></span>
            </div>
          </div>

          <span class="drop-bar" id="drop_bar"><i class="fa fa-bars"></i></span>
        </div>

        <div class="drop_aside">
          <div class="count count-two">
            <p>Total Drugs: 5</p>
          </div>

          <div class="search">
            {% include 'search/snippets/search-form.html' %}
          </div>

          <ul class="categories">
            <li>
              <i class="fa fa-medkit"></i>
              <a href="#" class="arrow"> Drugs</a>
              <ul class="resize-nav-dropdown">
                {% if request.user.is_admin %}

                <li><a href="{% url 'drug:register' %}">New Drug</a></li>
                <li>
                  <a href="{% url 'drug:pharmacy_drugs' pharmacy=pharmacy %}"
                    >My Drugs</a
                  >
                </li>
                <li>
                  <a href="{% url 'drug:expired_drugs' pharmacy=pharmacy %}"
                    >View expired Drugs</a
                  >
                </li>

                {% endif %}

                <li><a href="{% url 'drug:list' %}">All Drugs</a></li>
              </ul>
            </li>

            {% if request.user.is_pharmacist %}

            <li>
              <i class="fa fa-shopping-cart"></i>
              <a href="{% url 'drug:order_summary' %}">View Cart</a>
            </li>

            {% endif %} {% if request.user.is_admin %}

            <li>
              <i class="fa fa-group"></i>
              <a href="{% url 'core:pharmacist_list' pharmacy=pharmacy %}"
                >View list of Pharmacists</a
              >
            </li>

            {% endif %}

            <li>
              <i class="fa fa-user"></i>
              <a href="{% url 'core:profile' name=request.user.first_name %}"
                >Profile</a
              >
            </li>

            <li>
              <i class="fa fa-gear"></i>
              <a href="#" class="arrow"> Settings</a>
              <ul class="resize-nav-dropdown">
                <li>
                  <a class="" href="{% url 'account_change_password' %}"
                    >Change Password</a
                  >
                </li>
                <!-- <li><a href="{% url 'account_email' %}">Reset Email</a></li> -->
              </ul>
            </li>
            <li>
              <i class="fa fa-sign-out"></i>
              <a href="{% url 'account_logout' %}">Logout</a>
              <!-- <span class="bar"></span> -->
            </li>
          </ul>
        </div>
      </nav>

      <!-- this is where i'm starting -->
      <main>
        {% block content %} {% endblock %}
      </main>
    </section>

    <script src="{% static 'base/js/jquery.js' %}"></script>
    <script src="{% static 'base/js/notification_bell.js' %}"></script>
    <script src="{% static 'dashboard/js/dashboard.js' %}"></script>
    <script src="{% static 'dashboard/js/main_dashboard.js' %}"></script>
    <script src="{% static 'base/js/base.js' %}"></script>

    {% block js %} {% endblock %}
  </body>
</html>